openapi: 3.0.0
info:
  title: Remote Teacher-Parent Conferences System API
  description: An API for remote teacher-parent conferences system
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /login:
    post:
      summary: Sign in to the waiting queue of the conference
      description: A login page that guides parents through the steps to join the waiting queue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                homeroom:
                  type: string
                  description: Homeroom class name (e.g. 1A, 1B, 2A, 2B, 2C)
                studentNumber:
                  type: integer
                  description: Homeroom number of the student involved
                picture1:
                  type: string
                  format: binary
                  description: Picture of the first associated noun
                picture2:
                  type: string
                  format: binary
                  description: Picture of the second associated noun
              required:
                - homeroom
                - studentNumber
                - picture1
                - picture2
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the success of the login
                  queueNumber:
                    type: integer
                    description: The position of the parent in the waiting queue
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the reason for the bad request
  /waiting-queue:
    get:
      summary: Check the waiting queue status
      description: A waiting queue page that indicates the conference will start soon
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the status of the waiting queue
                  expectedStartTime:
                    type: string
                    format: date-time
                    description: The expected start time of the conference
                  position:
                    type: integer
                    description: The position of the parent in the waiting queue
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the waiting queue is not found
